server {
    listen 127.0.0.1:8080;
    root DIRECTORY/www/demo/;
    allow GET HEAD;
    autoindex on;
    max_request_body 1048576;
    
    location /scripts/*.py {
        allow GET POST;
        cgi /usr/bin/python3;
    }

    location /scripts/*.sh {
        allow GET POST;
        cgi /bin/sh;
    }
}
