# Setup the configuration file as follow:
# - / must answer to GET request ONLY
# - Any file with .bla as extension must answer to POST request by calling the cgi_test executable
# - /post_body must answer anything to POST request with a maxBody of 100
# - /directory/ must answer to GET request and the root of it would be the repository YoupiBanane and if no file are requested, it should search for youpi.bad_extension files

server{
  listen 127.0.0.1:8080;
  root DIRECTORY/www/42_tester/;
  allow GET;

  location /*.bla {
      allow POST;
      cgi /cgi_tester;
  }
  location /post_body {
      allow POST;
  	  max_request_body 100;
  }
  location /directory/ {
      allow GET;
      root /YoupiBanane/;
	  error_page 42 /youpi.bad_extension;
  }
}
