server     {
  max_request_body 888;
  listen 127.0.0.1:8080;
  root DIRECTORY/www/demo   ;
  autoindex off;
  allow GET   ;
}

server
{
  autoindex on;
  listen 127.0.0.1:880;
  listen 27.0.0.1:8080;
  listen 127.0.0.1:8080;
  root /www/var/ ;
}

server         {
  listen 127.0.0.1:8333380;
  root /;
  autoindex on;
}