server     {
  max_request_body 888;
  listen 127.0.0.1:8080;
  root DIRECTORY/www/demo/   ;
  autoindex on;
  allow GET   ;
}

server         {
  listen 127.0.0.1:8081;
  root DIRECTORY/www/this_site_has_no_index/;
  autoindex on;
  allow GET ;
}

server
{
  autoindex on;
  listen 127.0.0.1:8082;
  listen 127.0.0.1:8083;
  root DIRECTORY/www/secret_website/;
  allow GET ;
}
